//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstajoMailService.App_Code.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateEntities : DbContext
    {
        public RealEstateEntities()
            : base("name=RealEstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblAccountCompany> tblAccountCompanies { get; set; }
        public virtual DbSet<tblAccountIntegration> tblAccountIntegrations { get; set; }
        public virtual DbSet<tblLead> tblLeads { get; set; }
        public virtual DbSet<tblLeadEmailMessageAttachment> tblLeadEmailMessageAttachments { get; set; }
        public virtual DbSet<tblLeadEmailMessage> tblLeadEmailMessages { get; set; }
    }
}
