//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstajoMailService.App_Code.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountIntegration
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<int> AuthAccountType { get; set; }
        public string EmailAddress { get; set; }
        public string Name { get; set; }
        public Nullable<int> Expires_In { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
