//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstajoMailService.App_Code.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeadEmailMessageAttachment
    {
        public int LeadEmailMessageAttachmentId { get; set; }
        public Nullable<int> LeadEmailMessageId { get; set; }
        public string Attachement { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblLeadEmailMessage tblLeadEmailMessage { get; set; }
    }
}
