//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstajoMailService.App_Code.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLead()
        {
            this.tblLeadEmailMessages = new HashSet<tblLeadEmailMessage>();
        }
    
        public int LeadId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> CustomFieldId { get; set; }
        public string LeadSource { get; set; }
        public string LeadStatus { get; set; }
        public string Industry { get; set; }
        public string stage { get; set; }
        public string OwnerImg { get; set; }
        public string LeadOwner { get; set; }
        public string Company { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string MobileNumber { get; set; }
        public string Website { get; set; }
        public Nullable<int> NoOfEmp { get; set; }
        public Nullable<decimal> AnnualRevenue { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> EmailOptOut { get; set; }
        public string SkypeId { get; set; }
        public string TwitterId { get; set; }
        public string SecondaryEmail { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblAccount tblAccount1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeadEmailMessage> tblLeadEmailMessages { get; set; }
    }
}
