//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstajoMailService.App_Code.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeadEmailMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLeadEmailMessage()
        {
            this.tblLeadEmailMessageAttachments = new HashSet<tblLeadEmailMessageAttachment>();
        }
    
        public int LeadEmailMessageId { get; set; }
        public Nullable<int> LeadId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsReplay { get; set; }
        public Nullable<int> EmailMessageId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblLead tblLead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeadEmailMessageAttachment> tblLeadEmailMessageAttachments { get; set; }
    }
}
